export const data = [
	{
		numero: 1,
		nombre: 'Juan',
		correoElectronico: 'juan@example.com',
		telefono: '555-1234',
		encuesta: true,
	},
	{
		numero: 2,
		nombre: 'Ana',
		correoElectronico: 'ana@example.com',
		telefono: '555-5678',
		encuesta: false,
	},
	{
		numero: 3,
		nombre: 'Pedro',
		correoElectronico: 'pedro@example.com',
		telefono: '555-9012',
		encuesta: true,
	},
	{
		numero: 4,
		nombre: 'María',
		correoElectronico: 'maria@example.com',
		telefono: '555-3456',
		encuesta: false,
	},
	{
		numero: 5,
		nombre: 'Sofía',
		correoElectronico: 'sofia@example.com',
		telefono: '555-7890',
		encuesta: true,
	},
	{
		numero: 6,
		nombre: 'Carlos',
		correoElectronico: 'carlos@example.com',
		telefono: '555-2345',
		encuesta: false,
	},
	{
		numero: 7,
		nombre: 'Lucía',
		correoElectronico: 'lucia@example.com',
		telefono: '555-6789',
		encuesta: true,
	},
	{
		numero: 8,
		nombre: 'Andrés',
		correoElectronico: 'andres@example.com',
		telefono: '555-0123',
		encuesta: false,
	},
	{
		numero: 9,
		nombre: 'Isabel',
		correoElectronico: 'isabel@example.com',
		telefono: '555-4567',
		encuesta: true,
	},
	{
		numero: 10,
		nombre: 'José',
		correoElectronico: 'jose@example.com',
		telefono: '555-8901',
		encuesta: false,
	},
	{
		numero: 11,
		nombre: 'Verónica',
		correoElectronico: 'veronica@example.com',
		telefono: '555-2345',
		encuesta: true,
	},
	{
		numero: 12,
		nombre: 'Miguel',
		correoElectronico: 'miguel@example.com',
		telefono: '555-6789',
		encuesta: false,
	},
	{
		numero: 13,
		nombre: 'Adriana',
		correoElectronico: 'adriana@example.com',
		telefono: '555-0123',
		encuesta: true,
	},
	{
		numero: 14,
		nombre: 'Ricardo',
		correoElectronico: 'ricardo@example.com',
		telefono: '555-4567',
		encuesta: false,
	},
	{
		numero: 15,
		nombre: 'Laura',
		correoElectronico: 'laura@example.com',
		telefono: '444-8901',
		encuesta: true,
	},
];
